openapi: 3.0.0
info:
  version: 1.0.0
  title: Easy Tax Application
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: >-
    Introducing our user-friendly Easy Tax REST API, designed to simplify
    tax-related data integration. With our intuitive platform, preparing and
    submitting your taxes has never been easier. Say goodbye to complicated
    forms and confusing jargon; our application guides you through each step
    with clear, plain-language instructions.
  contact:
    name: Pixfar developer team
    url: https://pixfar.com
    email: pixfar@gmail.com
servers:
  - description: dev
    url: http://127.0.0.1:6050/api/v1
  - description: Production
    url: https://api.easy-tax.pixfar.com/api/v1
  - description: Easy Tax API
    url: https://api-fluxx.fluxx.co.nz/api/v1
tags:
  - name: Auth
    description: Authentication endpoints (public)
  - name: Expense
    description: Expense endpoint (private)
  - name: OCR
    description: OCR endpoints (private)
  - name: Category
    description: Category endpoints (private)
  - name: Income Source
    description: Income Source endpoints (private)
  - name: Admin
    description: User endpoint (private & admin)
  - name: Notification
    description: notification endpoints (private)

paths:
  # authentication
  /api/v1/auth/login:
    $ref: "./paths/auth/login.yaml"

components:
  parameters:
    $ref: "./components/parameters/_index.yaml"
  schemas:
    $ref: "./components/schemas/_index.yaml"
  responses:
    $ref: "components/responses/_index.yaml"

    # Security Definitions
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
