openapi: 3.0.0
info:
  version: 1.0.0
  title: Help Desk API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: >-
    "Help Desk" is a comprehensive customer support application designed to streamline and optimize customer service operations. With intuitive ticket management, efficient communication tools, and a robust knowledge base, Help Desk empowers organizations to provide prompt assistance and resolution to customer inquiries and issues. From ticket submission to resolution, Help Desk ensures a seamless support experience, enhancing customer satisfaction and loyalty.
  contact:
    name: Pixfar Development Team
    url: https://pixfar.com
    email: anamul@pixfar.com
servers:
  - description: Local Development
    url: http://127.0.0.1:6050
  - description: Production
    url: https://api.easy-tax.pixfar.com

tags:
  - name: Auth
    description: Authentication endpoints (public)
  - name: Category
    description: Category endpoints (private)
  - name: System
    description: System endpoints (private)
  - name: Team
    description: Team endpoints (private)
  - name: Ticket
    description: Ticket endpoints (private)
  - name: User
    description: User endpoints (private)

paths:
  # authentication
  /api/v1/auth/login:
    $ref: "./paths/auth/login.yaml"

components:
  parameters:
    $ref: "./components/parameters/_index.yaml"
  schemas:
    $ref: "./components/schemas/_index.yaml"
  responses:
    $ref: "components/responses/_index.yaml"

    # Security Definitions
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
