openapi: 3.0.0
info:
  version: 1.0.0
  title: Help Desk API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: >-
    "Help Desk" is a comprehensive customer support application designed to streamline and optimize customer service operations. With intuitive ticket management, efficient communication tools, and a robust knowledge base, Help Desk empowers organizations to provide prompt assistance and resolution to customer inquiries and issues. From ticket submission to resolution, Help Desk ensures a seamless support experience, enhancing customer satisfaction and loyalty.
  contact:
    name: Pixfar Development Team
    url: https://pixfar.com
    email: anamul@pixfar.com
servers:
  - description: Local Development
    url: http://127.0.0.1:6050
  - description: Production
    url: https://api.easy-tax.pixfar.com

tags:
  - name: Auth
    description: Authentication endpoints (public)
  - name: Category
    description: Category endpoints (private)
  - name: System
    description: System endpoints (private)
  - name: Team
    description: Team endpoints (private)
  - name: Ticket
    description: Ticket endpoints (private)
  - name: User
    description: User endpoints (private)

paths:
  # authentication
  /api/v1/auth/signup:
    $ref: "./paths/auth/signup.yaml"
  /api/v1/auth/login:
    $ref: "./paths/auth/login.yaml"
  /api/v1/auth/forgot-password:
    $ref: "./paths/auth/forgot-password.yaml"
  /api/v1/auth/reset-password:
    $ref: "./paths/auth/reset-password.yaml"
  /api/v1/auth/verify-token:
    $ref: paths/auth/verify-token.yaml
  /api/v1/auth/change-password:
    $ref: paths/auth/change-password.yaml
  /api/v1/auth/update-profile:
    $ref: paths/auth/update-profile.yaml
  /api/v1/auth/me:
    $ref: paths/auth/user-info.yaml
  /api/v1/auth/delete-account:
    $ref: paths/auth/delete-profile.yaml

  # category
  /api/v1/categories:
    $ref: paths/category/categories.yaml
  /api/v1/categories/{id}:
    $ref: paths/category/category.yaml
  /api/v1/categories/{id}/tickets:
    $ref: paths/category/tickets-by-category.yaml

  # system
  /api/v1/systems:
    $ref: paths/system/systems.yaml
  /api/v1/systems/{id}:
    $ref: paths/system/system.yaml

components:
  parameters:
    $ref: "./components/parameters/_index.yaml"
  schemas:
    $ref: "./components/schemas/_index.yaml"
  responses:
    $ref: "components/responses/_index.yaml"
  requestBodies:
    $ref: "./components/request-bodies/_index.yaml"

    # Security Definitions
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
