name: build image and push to the docker hub

on:
  push:
    branches:
      - master

jobs:
  test-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      # test auth service
      - name: Test auth service
        run: |
          cd services/auth
          yarn install --frozen-lockfile
          yarn test
      # test user service
      - name: Test user service
        run: |
          cd services/user
          yarn install --frozen-lockfile
          yarn test
      # test ticket service
      - name: Test ticket service
        run: |
          cd services/ticket
          yarn install --frozen-lockfile
          yarn test

  build-and-push:
    needs: test-services
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up QEMU
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build and push api-gateway
      - name: 'Build and push api-gateway'
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      # build and push auth-service
      - name: 'Build and push auth-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth
          file: ./services/auth/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      # build and push category-service
      - name: 'Build and push category-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/category
          file: ./services/category/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/category-service:latest

      # build and push notification-service
      - name: 'Build and push notification-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/notification
          file: ./services/notification/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

      # build and push system-service
      - name: 'Build and push system-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/system
          file: ./services/system/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/system-service:latest

      # build and push team-service
      - name: 'Build and push team-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/team
          file: ./services/team/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/team-service:latest

      # build and push user-service
      - name: 'Build and push user-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/user
          file: ./services/user/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      # build and push ticket-service
      - name: 'Build and push ticket-service'
        uses: docker/build-push-action@v5
        with:
          context: ./services/ticket
          file: ./services/ticket/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ticket-service:latest

      # build and push specification-service
      - name: 'Build and push specification-service'
        uses: docker/build-push-action@v5
        with:
          context: ./specification
          file: ./specification/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/specification-service:latest
