name: build image and push to the docker hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up QEMU
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build and push api-gateway
      - name: "Build and push api-gateway"
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      # build and push user-service
      - name: "Build and push user-service"
        uses: docker/build-push-action@v5
        with:
          context: ./services/user
          file: ./services/user/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

        # build and push ticket-service
      - name: "Build and push ticket-service"
        uses: docker/build-push-action@v5
        with:
          context: ./services/ticket
          file: ./services/ticket/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ticket-service:latest
